<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('bitrix_countries', function (Blueprint $table) {
            $table->id();
            $table->bigInteger('bitrix_id');
            $table->string('bitrix_name');
            $table->boolean('is_active')->default(1);
            $table->unsignedBigInteger('created_by')->default(0);
            $table->unsignedBigInteger('updated_by')->nullable();
            $table->timestamps();
        });

        DB::table('bitrix_countries')->insert([
            ["bitrix_id" => 24, "bitrix_name" => "Afghanistan"],
            ["bitrix_id" => 18, "bitrix_name" => "Albania"],
            ["bitrix_id" => 19, "bitrix_name" => "Algeria"],
            ["bitrix_id" => 146, "bitrix_name" => "Andorra"],
            ["bitrix_id" => 20, "bitrix_name" => "Angola"],
            ["bitrix_id" => 182, "bitrix_name" => "Anguilla"],
            ["bitrix_id" => 183, "bitrix_name" => "Antarctica"],
            ["bitrix_id" => 184, "bitrix_name" => "Antigua and Barbuda"],
            ["bitrix_id" => 22, "bitrix_name" => "Argentina"],
            ["bitrix_id" => 3, "bitrix_name" => "Armenia"],
            ["bitrix_id" => 23, "bitrix_name" => "Aruba"],
            ["bitrix_id" => 16, "bitrix_name" => "Australia"],
            ["bitrix_id" => 17, "bitrix_name" => "Austria"],
            ["bitrix_id" => 2, "bitrix_name" => "Azerbaijan"],
            ["bitrix_id" => 25, "bitrix_name" => "Bahamas"],
            ["bitrix_id" => 145, "bitrix_name" => "Bahrain"],
            ["bitrix_id" => 26, "bitrix_name" => "Bangladesh"],
            ["bitrix_id" => 27, "bitrix_name" => "Barbados"],
            ["bitrix_id" => 4, "bitrix_name" => "Belarus"],
            ["bitrix_id" => 28, "bitrix_name" => "Belgium"],
            ["bitrix_id" => 147, "bitrix_name" => "Belize"],
            ["bitrix_id" => 29, "bitrix_name" => "Benin"],
            ["bitrix_id" => 30, "bitrix_name" => "Bermuda"],
            ["bitrix_id" => 148, "bitrix_name" => "Bhutan"],
            ["bitrix_id" => 32, "bitrix_name" => "Bolivia"],
            ["bitrix_id" => 33, "bitrix_name" => "Bosnia and Herzegowina"],
            ["bitrix_id" => 149, "bitrix_name" => "Botswana"],
            ["bitrix_id" => 185, "bitrix_name" => "Bouvet Island"],
            ["bitrix_id" => 34, "bitrix_name" => "Brazil"],
            ["bitrix_id" => 186, "bitrix_name" => "British Indian Ocean Territory"],
            ["bitrix_id" => 187, "bitrix_name" => "British Virgin Islands"],
            ["bitrix_id" => 35, "bitrix_name" => "Brunei Darussalam"],
            ["bitrix_id" => 31, "bitrix_name" => "Bulgaria"],
            ["bitrix_id" => 150, "bitrix_name" => "Burkina Faso"],
            ["bitrix_id" => 151, "bitrix_name" => "Burundi"],
            ["bitrix_id" => 78, "bitrix_name" => "Cambodia"],
            ["bitrix_id" => 72, "bitrix_name" => "Cameroon"],
            ["bitrix_id" => 73, "bitrix_name" => "Canada"],
            ["bitrix_id" => 189, "bitrix_name" => "Cape Verde"],
            ["bitrix_id" => 71, "bitrix_name" => "Cayman Islands"],
            ["bitrix_id" => 152, "bitrix_name" => "Central African Republic"],
            ["bitrix_id" => 133, "bitrix_name" => "Chad"],
            ["bitrix_id" => 135, "bitrix_name" => "Chile"],
            ["bitrix_id" => 76, "bitrix_name" => "China"],
            ["bitrix_id" => 190, "bitrix_name" => "Christmas Island"],
            ["bitrix_id" => 191, "bitrix_name" => "Cocos Islands"],
            ["bitrix_id" => 77, "bitrix_name" => "Colombia"],
            ["bitrix_id" => 153, "bitrix_name" => "Comoros"],
            ["bitrix_id" => 79, "bitrix_name" => "Congo"],
            ["bitrix_id" => 192, "bitrix_name" => "Cook Islands"],
            ["bitrix_id" => 81, "bitrix_name" => "Costa Rica"],
            ["bitrix_id" => 154, "bitrix_name" => "Cote D'ivoire"],
            ["bitrix_id" => 181, "bitrix_name" => "Croatia"],
            ["bitrix_id" => 82, "bitrix_name" => "Cuba"],
            ["bitrix_id" => 75, "bitrix_name" => "Cyprus"],
            ["bitrix_id" => 134, "bitrix_name" => "Czechia"],
            ["bitrix_id" => 54, "bitrix_name" => "Denmark"],
            ["bitrix_id" => 155, "bitrix_name" => "Djibouti"],
            ["bitrix_id" => 193, "bitrix_name" => "Dominica"],
            ["bitrix_id" => 55, "bitrix_name" => "Dominican Republic"],
            ["bitrix_id" => 156, "bitrix_name" => "East Timor"],
            ["bitrix_id" => 139, "bitrix_name" => "Ecuador"],
            ["bitrix_id" => 56, "bitrix_name" => "Egypt"],
            ["bitrix_id" => 157, "bitrix_name" => "El Salvador"],
            ["bitrix_id" => 158, "bitrix_name" => "Equatorial Guinea"],
            ["bitrix_id" => 159, "bitrix_name" => "Eritrea"],
            ["bitrix_id" => 15, "bitrix_name" => "Estonia"],
            ["bitrix_id" => 140, "bitrix_name" => "Ethiopia"],
            ["bitrix_id" => 195, "bitrix_name" => "Faeroe Islands"],
            ["bitrix_id" => 194, "bitrix_name" => "Falkland Islands"],
            ["bitrix_id" => 160, "bitrix_name" => "Fiji"],
            ["bitrix_id" => 131, "bitrix_name" => "Finland"],
            ["bitrix_id" => 132, "bitrix_name" => "France"],
            ["bitrix_id" => 198, "bitrix_name" => "French Antarctic"],
            ["bitrix_id" => 196, "bitrix_name" => "French Guiana"],
            ["bitrix_id" => 197, "bitrix_name" => "French Polynesia"],
            ["bitrix_id" => 161, "bitrix_name" => "Gabon"],
            ["bitrix_id" => 41, "bitrix_name" => "Gambia"],
            ["bitrix_id" => 5, "bitrix_name" => "Georgia"],
            ["bitrix_id" => 46, "bitrix_name" => "Germany"],
            ["bitrix_id" => 162, "bitrix_name" => "Ghana"],
            ["bitrix_id" => 47, "bitrix_name" => "Gibraltar"],
            ["bitrix_id" => 52, "bitrix_name" => "Greece"],
            ["bitrix_id" => 51, "bitrix_name" => "Greenland"],
            ["bitrix_id" => 50, "bitrix_name" => "Grenada"],
            ["bitrix_id" => 43, "bitrix_name" => "Guadeloupe"],
            ["bitrix_id" => 44, "bitrix_name" => "Guatemala"],
            ["bitrix_id" => 45, "bitrix_name" => "Guinea"],
            ["bitrix_id" => 163, "bitrix_name" => "Guinea-bissau"],
            ["bitrix_id" => 53, "bitrix_name" => "Guyana"],
            ["bitrix_id" => 40, "bitrix_name" => "Haiti"],
            ["bitrix_id" => 199, "bitrix_name" => "Heard and McDonald Islands"],
            ["bitrix_id" => 42, "bitrix_name" => "Honduras"],
            ["bitrix_id" => 49, "bitrix_name" => "Hong Kong"],
            ["bitrix_id" => 37, "bitrix_name" => "Hungary"],
            ["bitrix_id" => 67, "bitrix_name" => "Iceland"],
            ["bitrix_id" => 61, "bitrix_name" => "India"],
            ["bitrix_id" => 62, "bitrix_name" => "Indonesia"],
            ["bitrix_id" => 65, "bitrix_name" => "Iran"],
            ["bitrix_id" => 64, "bitrix_name" => "Iraq"],
            ["bitrix_id" => 66, "bitrix_name" => "Ireland"],
            ["bitrix_id" => 60, "bitrix_name" => "Israel"],
            ["bitrix_id" => 69, "bitrix_name" => "Italy"],
            ["bitrix_id" => 143, "bitrix_name" => "Jamaica"],
            ["bitrix_id" => 144, "bitrix_name" => "Japan"],
            ["bitrix_id" => 63, "bitrix_name" => "Jordan"],
            ["bitrix_id" => 6, "bitrix_name" => "Kazakhstan"],
            ["bitrix_id" => 74, "bitrix_name" => "Kenya"],
            ["bitrix_id" => 200, "bitrix_name" => "Kiribati"],
            ["bitrix_id" => 164, "bitrix_name" => "Korea (North)"],
            ["bitrix_id" => 80, "bitrix_name" => "Korea (South)"],
            ["bitrix_id" => 83, "bitrix_name" => "Kuwait"],
            ["bitrix_id" => 7, "bitrix_name" => "Kyrgyzstan"],
            ["bitrix_id" => 201, "bitrix_name" => "Laos"],
            ["bitrix_id" => 8, "bitrix_name" => "Latvia"],
            ["bitrix_id" => 165, "bitrix_name" => "Lebanon"],
            ["bitrix_id" => 166, "bitrix_name" => "Lesotho"],
            ["bitrix_id" => 84, "bitrix_name" => "Liberia"],
            ["bitrix_id" => 167, "bitrix_name" => "Libya"],
            ["bitrix_id" => 85, "bitrix_name" => "Liechtenstein"],
            ["bitrix_id" => 9, "bitrix_name" => "Lithuania"],
            ["bitrix_id" => 86, "bitrix_name" => "Luxembourg"],
            ["bitrix_id" => 202, "bitrix_name" => "Macau"],
            ["bitrix_id" => 89, "bitrix_name" => "Macedonia"],
            ["bitrix_id" => 88, "bitrix_name" => "Madagascar"],
            ["bitrix_id" => 203, "bitrix_name" => "Malawi"],
            ["bitrix_id" => 90, "bitrix_name" => "Malaysia"],
            ["bitrix_id" => 91, "bitrix_name" => "Mali"],
            ["bitrix_id" => 92, "bitrix_name" => "Malta"],
            ["bitrix_id" => 168, "bitrix_name" => "Malvides"],
            ["bitrix_id" => 169, "bitrix_name" => "Marshall Islands"],
            ["bitrix_id" => 204, "bitrix_name" => "Martinique"],
            ["bitrix_id" => 87, "bitrix_name" => "Mauritania"],
            ["bitrix_id" => 205, "bitrix_name" => "Mauritius"],
            ["bitrix_id" => 206, "bitrix_name" => "Mayotte"],
            ["bitrix_id" => 93, "bitrix_name" => "Mexico"],
            ["bitrix_id" => 207, "bitrix_name" => "Micronesia"],
            ["bitrix_id" => 10, "bitrix_name" => "Moldova"],
            ["bitrix_id" => 95, "bitrix_name" => "Monaco"],
            ["bitrix_id" => 96, "bitrix_name" => "Mongolia"],
            ["bitrix_id" => 236, "bitrix_name" => "Montenegro"],
            ["bitrix_id" => 208, "bitrix_name" => "Montserrat"],
            ["bitrix_id" => 97, "bitrix_name" => "Morocco"],
            ["bitrix_id" => 94, "bitrix_name" => "Mozambique"],
            ["bitrix_id" => 188, "bitrix_name" => "Myanmar"],
            ["bitrix_id" => 98, "bitrix_name" => "Namibia"],
            ["bitrix_id" => 209, "bitrix_name" => "Nauru"],
            ["bitrix_id" => 99, "bitrix_name" => "Nepal"],
            ["bitrix_id" => 48, "bitrix_name" => "Netherlands"],
            ["bitrix_id" => 210, "bitrix_name" => "Netherlands Antilles"],
            ["bitrix_id" => 211, "bitrix_name" => "New Caledonia"],
            ["bitrix_id" => 103, "bitrix_name" => "New Zealand"],
            ["bitrix_id" => 102, "bitrix_name" => "Nicaragua"],
            ["bitrix_id" => 170, "bitrix_name" => "Niger"],
            ["bitrix_id" => 100, "bitrix_name" => "Nigeria"],
            ["bitrix_id" => 212, "bitrix_name" => "Niue"],
            ["bitrix_id" => 213, "bitrix_name" => "Norfolk Island"],
            ["bitrix_id" => 104, "bitrix_name" => "Norway"],
            ["bitrix_id" => 171, "bitrix_name" => "Oman"],
            ["bitrix_id" => 105, "bitrix_name" => "Pakistan"],
            ["bitrix_id" => 214, "bitrix_name" => "Palau"],
            ["bitrix_id" => 215, "bitrix_name" => "Palestine"],
            ["bitrix_id" => 106, "bitrix_name" => "Panama"],
            ["bitrix_id" => 107, "bitrix_name" => "Papua New Guinea"],
            ["bitrix_id" => 108, "bitrix_name" => "Paraguay"],
            ["bitrix_id" => 109, "bitrix_name" => "Peru"],
            ["bitrix_id" => 130, "bitrix_name" => "Philippines"],
            ["bitrix_id" => 216, "bitrix_name" => "Pitcairn Islands"],
            ["bitrix_id" => 110, "bitrix_name" => "Poland"],
            ["bitrix_id" => 111, "bitrix_name" => "Portugal"],
            ["bitrix_id" => 112, "bitrix_name" => "Puerto Rico"],
            ["bitrix_id" => 172, "bitrix_name" => "Qatar"],
            ["bitrix_id" => 217, "bitrix_name" => "Reunion"],
            ["bitrix_id" => 113, "bitrix_name" => "Romania"],
            ["bitrix_id" => 1, "bitrix_name" => "Russia"],
            ["bitrix_id" => 173, "bitrix_name" => "Rwanda"],
            ["bitrix_id" => 218, "bitrix_name" => "Saint Helena"],
            ["bitrix_id" => 219, "bitrix_name" => "Saint Kitts and Nevis"],
            ["bitrix_id" => 220, "bitrix_name" => "Saint Lucia"],
            ["bitrix_id" => 222, "bitrix_name" => "Saint Vincent and the Grenadines"],
            ["bitrix_id" => 221, "bitrix_name" => "Saint-Pierre and Miquelon"],
            ["bitrix_id" => 174, "bitrix_name" => "Samoa"],
            ["bitrix_id" => 223, "bitrix_name" => "San Marino"],
            ["bitrix_id" => 114, "bitrix_name" => "Saudi Arabia"],
            ["bitrix_id" => 115, "bitrix_name" => "Senegal"],
            ["bitrix_id" => 142, "bitrix_name" => "Serbia"],
            ["bitrix_id" => 175, "bitrix_name" => "Seychelles"],
            ["bitrix_id" => 176, "bitrix_name" => "Sierra Leone"],
            ["bitrix_id" => 116, "bitrix_name" => "Singapore"],
            ["bitrix_id" => 118, "bitrix_name" => "Slovakia"],
            ["bitrix_id" => 119, "bitrix_name" => "Slovenia"],
            ["bitrix_id" => 224, "bitrix_name" => "Solomon Islands"],
            ["bitrix_id" => 120, "bitrix_name" => "Somalia"],
            ["bitrix_id" => 141, "bitrix_name" => "South African Republic"],
            ["bitrix_id" => 225, "bitrix_name" => "South Georgia and the South Sandwich Islands"],
            ["bitrix_id" => 68, "bitrix_name" => "Spain"],
            ["bitrix_id" => 138, "bitrix_name" => "Sri Lanka"],
            ["bitrix_id" => 121, "bitrix_name" => "Sudan"],
            ["bitrix_id" => 177, "bitrix_name" => "Suriname"],
            ["bitrix_id" => 226, "bitrix_name" => "Svalbard and Jan Mayen Islands"],
            ["bitrix_id" => 178, "bitrix_name" => "Swaziland"],
            ["bitrix_id" => 137, "bitrix_name" => "Sweden"],
            ["bitrix_id" => 136, "bitrix_name" => "Switzerland"],
            ["bitrix_id" => 117, "bitrix_name" => "Syria"],
            ["bitrix_id" => 123, "bitrix_name" => "Taiwan"],
            ["bitrix_id" => 11, "bitrix_name" => "Tajikistan"],
            ["bitrix_id" => 179, "bitrix_name" => "Tanzania"],
            ["bitrix_id" => 124, "bitrix_name" => "Thailand"],
            ["bitrix_id" => 227, "bitrix_name" => "Togo"],
            ["bitrix_id" => 228, "bitrix_name" => "Tokelau"],
            ["bitrix_id" => 229, "bitrix_name" => "Tonga"],
            ["bitrix_id" => 125, "bitrix_name" => "Trinidad and Tobago"],
            ["bitrix_id" => 126, "bitrix_name" => "Tunisia"],
            ["bitrix_id" => 127, "bitrix_name" => "Turkey"],
            ["bitrix_id" => 12, "bitrix_name" => "Turkmenistan"],
            ["bitrix_id" => 230, "bitrix_name" => "Turks Caicos Islands"],
            ["bitrix_id" => 231, "bitrix_name" => "Tuvalu"],
            ["bitrix_id" => 232, "bitrix_name" => "U.S. Virgin Islands"],
            ["bitrix_id" => 122, "bitrix_name" => "USA"],
            ["bitrix_id" => 128, "bitrix_name" => "Uganda"],
            ["bitrix_id" => 14, "bitrix_name" => "Ukraine"],
            ["bitrix_id" => 21, "bitrix_name" => "United Arab Emirates"],
            ["bitrix_id" => 36, "bitrix_name" => "United Kingdom"],
            ["bitrix_id" => 129, "bitrix_name" => "Uruguay"],
            ["bitrix_id" => 13, "bitrix_name" => "Uzbekistan"],
            ["bitrix_id" => 233, "bitrix_name" => "Vanuatu"],
            ["bitrix_id" => 234, "bitrix_name" => "Vatican City"],
            ["bitrix_id" => 38, "bitrix_name" => "Venezuela"],
            ["bitrix_id" => 39, "bitrix_name" => "Viet Nam"],
            ["bitrix_id" => 235, "bitrix_name" => "Wallis and Futuna Islands"],
            ["bitrix_id" => 180, "bitrix_name" => "Western Sahara"],
            ["bitrix_id" => 70, "bitrix_name" => "Yemen"],
            ["bitrix_id" => 57, "bitrix_name" => "Zaire"],
            ["bitrix_id" => 58, "bitrix_name" => "Zambia"],
            ["bitrix_id" => 59, "bitrix_name" => "Zimbabwe"]
        ]);
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('bitrix_countries');
    }
};
